USE [CoffeeAPI]
GO

/****** Object:  Table [dbo].[UserRating]    Script Date: 31/10/2020 10:27:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UserRating](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Comment] [nvarchar](50) NOT NULL,
	[RatingValue] [int] NOT NULL,
 CONSTRAINT [PK_UserRating] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


